// This file is auto-generated by scripts/sync-hotlink-sites-from-immersive.cjs
// Do not edit manually.

/* cspell:disable */

export interface GeneratedHotlinkSiteRule {
    ruleKey: string
    matchHostPattern: string
    referer: string
    origin?: string
    priority: number
}

export const GENERATED_HOTLINK_SITE_RULES: GeneratedHotlinkSiteRule[] = [
    {
        ruleKey: "immersive-301",
        matchHostPattern: "^i\\.pximg\\.net$",
        referer: "https://www.pixiv.net/",
        priority: 101
    },
    {
        ruleKey: "immersive-302",
        matchHostPattern: "^img1\\.newtoki21.*\\.org$",
        referer: "https://newtoki341.com/",
        priority: 101
    },
    {
        ruleKey: "immersive-303",
        matchHostPattern: "^img1\\.newtoki21\\.org$",
        referer: "https://newtoki341.com/",
        priority: 101
    },
    {
        ruleKey: "immersive-304",
        matchHostPattern: "^2\\.bp\\.blogspot\\.com$",
        referer: "https://2.bp.blogspot.com",
        priority: 101
    },
    {
        ruleKey: "immersive-305",
        matchHostPattern: "^japanreader\\.com$",
        referer: "https://japanreader.com",
        priority: 101
    },
    {
        ruleKey: "immersive-307",
        matchHostPattern: "^sl\\.mangafuna\\.xyz$",
        referer: "https://sl.mangafuna.xyz/",
        priority: 101
    },
    {
        ruleKey: "immersive-308",
        matchHostPattern: "^s.*\\.toonilycdnv2\\.xyz$",
        referer: "https://toonily.me",
        priority: 101
    },
    {
        ruleKey: "immersive-309",
        matchHostPattern: "^.*\\.whatsnew.*\\.net$",
        referer: "https://readcomiconline.li",
        priority: 101
    },
    {
        ruleKey: "immersive-310",
        matchHostPattern: "^image\\.yymanhua\\.com$",
        referer: "https://yymanhua.com",
        priority: 101
    },
    {
        ruleKey: "immersive-312",
        matchHostPattern: "^stcdn\\.manhwato\\.com$",
        referer: "https://manhwato.com",
        priority: 101
    },
    {
        ruleKey: "immersive-313",
        matchHostPattern: "^.*\\.kingwar\\.cn$",
        referer: "https://www.comemh8.com",
        priority: 101
    },
    {
        ruleKey: "immersive-314",
        matchHostPattern: "^.*\\.sinaimg\\.cn$",
        referer: "https://weibo.com/",
        priority: 101
    },
    {
        ruleKey: "immersive-317",
        matchHostPattern: "^.*\\.jfimv2\\.xyz$",
        referer: "https://jestful.net",
        priority: 101
    },
    {
        ruleKey: "immersive-318",
        matchHostPattern: "^viewer\\.championcross\\.jp$",
        referer: "https://viewer.championcross.jp",
        priority: 101
    },
    {
        ruleKey: "immersive-319",
        matchHostPattern: "^viewer\\.comic-growl\\.com$",
        referer: "https://viewer.comic-growl.com/",
        priority: 101
    },
]

export const GENERATED_HOTLINK_SITE_RULES_META = {
    sourcePath: "src\\public\\assets\\request_modifier_rule.json",
    sourceHash: "df7f95095169fe949938fd886eab349a36137e515a8fe60c3728867fc9ac543b",
    totalInputRules: 16,
    totalOutputRules: 15,
    skippedRules: 1
}

/* cspell:enable */
